# Generated by Django 4.2.11 on 2024-04-25 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_team_leader_alter_player_team_alter_team_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="id",
        ),
        migrations.AlterField(
            model_name="player",
            name="profile_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=4,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=4,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
