# Generated by Django 4.2.11 on 2024-04-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_notifications_player_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="notifications",
        ),
        migrations.AddField(
            model_name="team",
            name="notifications",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.notifications",
            ),
        ),
    ]
