# Generated by Django 4.2.11 on 2024-04-26 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_team_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_id",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=4),
        ),
    ]
