# Generated by Django 4.2.11 on 2024-04-26 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_team_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="team_id",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=4),
        ),
    ]
