# Generated by Django 4.2.11 on 2024-04-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_tournament_team_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="team_id",
            new_name="tournament_id",
        ),
    ]
