# Generated by Django 4.2.11 on 2024-04-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_team_id_tournament_tournament_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
